### ISSUE TITLE
Add TxInfo and ScriptContext for completeness (both V1 and V2)

### ISSUE THREAD

**Issue by bladyjoker** [mlabs-haskell/plutus-ledger-api-typescript#12]
See https://github.com/mlabs-haskell/plutus-ledger-api-rust/pull/11

**Comment by jaredponn** [comment]
- [x] V1 TxInfo is added in: #29

**Comment by bladyjoker** [comment]
Hey @jaredponn I'm hitting this in https://github.com/mlabs-haskell/lambda-buffers/pull/227

Can you add V1 ScriptPurpose and ScriptContext and V2 TxInfo and ScriptContext?

I already scafolded the LB part in https://github.com/mlabs-haskell/lambda-buffers/pull/227/commits/5fc3d1cff119e21aacb2efaf1df58208b2165965
